version: '3.7'
services:
  server:
    environment:
      - NODE_ENV=prod
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - database
  database:
      image: mongo
      container_name: mongodb
      volumes:
        - ./mongo-volume:/data/db
      restart: always
      ports:
          - 27017:27017